# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/webserver"
  bin = "tmp/webserver"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  follow_symlink = true

[log]
  time = true
