services:
  postgres:
    image: postgres:16.6
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mendel_core
    volumes:
      - ./server/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mendel

  webserver:
    build:
      context: ./server
      target: dev
    container_name: webserver
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgres://admin:password@postgres:5432/mendel_core
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 2s
      retries: 3
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    networks:
      - mendel
    profiles:
      - dev

  web:
    image: node:20
    container_name: web
    working_dir: /app
    environment:
      - SERVER_URL=http://webserver:8080
    networks:
      - mendel
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
    command: >
      sh -c "npm install &&
             mkdir -p logs &&
             npm run dev &
             npm run test
             wait"
    depends_on:
      - postgres
      - webserver

volumes:
  postgres_data:

networks:
  mendel:
