services:
  postgres:
    image: postgres:16.6
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mendel_core
    volumes:
      - ./server/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mendel_network

  mendel-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: dev
    env_file:
      - ./server/.env.dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 2s
      retries: 3
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    networks:
      - mendel_network
    depends_on:
      - postgres
    profiles:
      - dev

  mendel_web:
    image: node:20
    container_name: web
    working_dir: /app
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    networks:
      - mendel_network
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
    command: >
      sh -c "npm install &&
             mkdir -p logs &&
             npm run dev
             wait"
    depends_on:
      - postgres
      - mendel
    profiles:
      - dev

volumes:
  postgres_data:

networks:
  mendel_network:
